gpu: 0
epochs: 1
batch_size: 1
model_type: 'RHA'
network_n_sources: 2
network_num_filters_in_encoder: 64
network_num_head_per_att: 8
network_dim_key_att: 1024
network_num_tran_blocks: 1
network_num_chop_blocks: 1
network_chunk_size: 256
data_set: '/data/sample_data'
max_input_length_in_seconds: 5
samplerate_hz: 8000
lr: .0001
